name: Java with Maven CI

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    # Step 1: Check out the repository code
    - uses: actions/checkout@v3

    # Step 2: Set up JDK 17 (you can change the version as needed)
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'          # Specify the Java version
        distribution: 'temurin'     # Use the Adoptium Temurin distribution
        cache: maven                # Cache Maven dependencies to speed up builds

    # Step 3: Build the project and run tests with Maven
    - name: Build and Test with Maven
      run: mvn --batch-mode --update-snapshots verify  # Runs the Maven 'verify' phase, which includes tests

    # Step 4: Package the build artifacts (e.g., JAR files)
    - name: Package and Upload Artifacts
      run: |
        mkdir staging               # Create a staging directory
        cp target/*.jar staging      # Copy the JAR file(s) to the staging directory
    - uses: actions/upload-artifact@v4
      with:
        name: java-artifacts         # Artifact name (can be anything)
        path: staging                # Path to the directory containing the files to upload
